services:
  delivery_db:
    container_name: delivery_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5522:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  api:
    container_name: delivery_storage_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - delivery_db
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=delivery_db;Database=delivery_db;Username=postgres;Password=postgres

volumes:
  postgres-data: