// <auto-generated />
using System;
using DeliveryStorage.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryStorage.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryStorage.Database.Entities.BoxDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<Guid?>("PalletId1")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PalletId1");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("DeliveryStorage.Database.Entities.PalletDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("DeliveryStorage.Database.Entities.BoxDb", b =>
                {
                    b.HasOne("DeliveryStorage.Database.Entities.PalletDb", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId1");

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("DeliveryStorage.Database.Entities.PalletDb", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
